There are 2 ways to use secrets in your pod.yml
################## 1)  using secret in pod.yml with env #######################
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-1
spec:
  containers:
  - name: demo-container
    image: nginx
    env:
    - name: Username
      valueFrom:   
        secretKeyRef:   
          name: db-secret
          key: username


################## 2)  using secret in pod.yml with envFrom #######################

apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-2
spec:
  containers:
  - name: demo-container
    image: nginx
    envFrom:
    - secretRef:
       name: docker-secret
          

###### Secret.yml ####################

apiVersion: v1
kind: Secret
metadata: 
  namespace: ask360-ns
  name: superset-geniq-sec
type: Opaque
data:  
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=

#Command to encord the value after creating the k8'S cluster!!

#Encode
#echo -n "V3r1R33EYp$ssw" | base64  

#Decode
#echo 'V3r1R33EYp$ssw' | base64 --decode
  
